AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Exclude:
    - ext/ruar/extconf.rb
    - tmp/**/*
    - pkg/**/*
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
